//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class LopHoc : BaseEntity
    {
        public LopHoc()
        {
            this.MultiTests = new HashSet<MultiTest>();
            this.Tests = new HashSet<Test>();
        }
    
    	private int m_ClassId;
    	private string m_ClassName;
    	private string m_ClassNo;
        public int ClassId {
    		get{ 
    			return m_ClassId;
    		} 
    		set{ 
    			if(m_ClassId != value){
    				m_ClassId = value; 
    				NotifyPropertyChanged("ClassId"); 
                }
    		} 
    	}
    	[DataMember]
        public string ClassName {
    		get{ 
    			return m_ClassName;
    		} 
    		set{ 
    			if(m_ClassName != value){
    				m_ClassName = value; 
    				NotifyPropertyChanged("ClassName"); 
                }
    		} 
    	}
    	[DataMember]
        public string ClassNo {
    		get{ 
    			return m_ClassNo;
    		} 
    		set{ 
    			if(m_ClassNo != value){
    				m_ClassNo = value; 
    				NotifyPropertyChanged("ClassNo"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((LopHoc)dest).ClassId = ((LopHoc)source).ClassId;
    		((LopHoc)dest).ClassName = ((LopHoc)source).ClassName;
    		((LopHoc)dest).ClassNo = ((LopHoc)source).ClassNo;
    	}
    
    
        public virtual ICollection<MultiTest> MultiTests { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
    }
}
