//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class MultiTestQuestion : BaseEntity
    {
    	private long m_FK_MultiTestId;
    	private long m_FK_QuestionId;
    	private Nullable<double> m_Mark;
        public long FK_MultiTestId {
    		get{ 
    			return m_FK_MultiTestId;
    		} 
    		set{ 
    			if(m_FK_MultiTestId != value){
    				m_FK_MultiTestId = value; 
    				NotifyPropertyChanged("FK_MultiTestId"); 
                }
    		} 
    	}
        public long FK_QuestionId {
    		get{ 
    			return m_FK_QuestionId;
    		} 
    		set{ 
    			if(m_FK_QuestionId != value){
    				m_FK_QuestionId = value; 
    				NotifyPropertyChanged("FK_QuestionId"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<double> Mark {
    		get{ 
    			return m_Mark;
    		} 
    		set{ 
    			if(m_Mark != value){
    				m_Mark = value; 
    				NotifyPropertyChanged("Mark"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((MultiTestQuestion)dest).FK_MultiTestId = ((MultiTestQuestion)source).FK_MultiTestId;
    		((MultiTestQuestion)dest).FK_QuestionId = ((MultiTestQuestion)source).FK_QuestionId;
    		((MultiTestQuestion)dest).Mark = ((MultiTestQuestion)source).Mark;
    	}
    
    
        public virtual MultiTest MultiTest { get; set; }
        public virtual Question Question { get; set; }
    }
}
