//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Operation : BaseEntity
    {
    	private int m_ID;
    	private string m_OperationName;
        public int ID {
    		get{ 
    			return m_ID;
    		} 
    		set{ 
    			if(m_ID != value){
    				m_ID = value; 
    				NotifyPropertyChanged("ID"); 
                }
    		} 
    	}
    	[DataMember]
        public string OperationName {
    		get{ 
    			return m_OperationName;
    		} 
    		set{ 
    			if(m_OperationName != value){
    				m_OperationName = value; 
    				NotifyPropertyChanged("OperationName"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((Operation)dest).ID = ((Operation)source).ID;
    		((Operation)dest).OperationName = ((Operation)source).OperationName;
    	}
    
    }
}
