//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class SchoolInfo : BaseEntity
    {
    	private int m_SchoolInfoId;
    	private string m_SchoolName;
    	private string m_HomePhone;
    	private string m_Phone;
    	private string m_Email;
    	private bool m_IsActive;
        public int SchoolInfoId {
    		get{ 
    			return m_SchoolInfoId;
    		} 
    		set{ 
    			if(m_SchoolInfoId != value){
    				m_SchoolInfoId = value; 
    				NotifyPropertyChanged("SchoolInfoId"); 
                }
    		} 
    	}
    	[DataMember]
        public string SchoolName {
    		get{ 
    			return m_SchoolName;
    		} 
    		set{ 
    			if(m_SchoolName != value){
    				m_SchoolName = value; 
    				NotifyPropertyChanged("SchoolName"); 
                }
    		} 
    	}
    	[DataMember]
        public string HomePhone {
    		get{ 
    			return m_HomePhone;
    		} 
    		set{ 
    			if(m_HomePhone != value){
    				m_HomePhone = value; 
    				NotifyPropertyChanged("HomePhone"); 
                }
    		} 
    	}
    	[DataMember]
        public string Phone {
    		get{ 
    			return m_Phone;
    		} 
    		set{ 
    			if(m_Phone != value){
    				m_Phone = value; 
    				NotifyPropertyChanged("Phone"); 
                }
    		} 
    	}
    	[DataMember]
        public string Email {
    		get{ 
    			return m_Email;
    		} 
    		set{ 
    			if(m_Email != value){
    				m_Email = value; 
    				NotifyPropertyChanged("Email"); 
                }
    		} 
    	}
    	[DataMember]
        public bool IsActive {
    		get{ 
    			return m_IsActive;
    		} 
    		set{ 
    			if(m_IsActive != value){
    				m_IsActive = value; 
    				NotifyPropertyChanged("IsActive"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((SchoolInfo)dest).SchoolInfoId = ((SchoolInfo)source).SchoolInfoId;
    		((SchoolInfo)dest).SchoolName = ((SchoolInfo)source).SchoolName;
    		((SchoolInfo)dest).HomePhone = ((SchoolInfo)source).HomePhone;
    		((SchoolInfo)dest).Phone = ((SchoolInfo)source).Phone;
    		((SchoolInfo)dest).Email = ((SchoolInfo)source).Email;
    		((SchoolInfo)dest).IsActive = ((SchoolInfo)source).IsActive;
    	}
    
    }
}
