//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class StudentTestDetail : BaseEntity
    {
    	private long m_FK_TestId;
    	private long m_FK_StudentId;
    	private long m_FK_QuestionId;
    	private Nullable<long> m_FK_AnserId;
        public long FK_TestId {
    		get{ 
    			return m_FK_TestId;
    		} 
    		set{ 
    			if(m_FK_TestId != value){
    				m_FK_TestId = value; 
    				NotifyPropertyChanged("FK_TestId"); 
                }
    		} 
    	}
        public long FK_StudentId {
    		get{ 
    			return m_FK_StudentId;
    		} 
    		set{ 
    			if(m_FK_StudentId != value){
    				m_FK_StudentId = value; 
    				NotifyPropertyChanged("FK_StudentId"); 
                }
    		} 
    	}
        public long FK_QuestionId {
    		get{ 
    			return m_FK_QuestionId;
    		} 
    		set{ 
    			if(m_FK_QuestionId != value){
    				m_FK_QuestionId = value; 
    				NotifyPropertyChanged("FK_QuestionId"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<long> FK_AnserId {
    		get{ 
    			return m_FK_AnserId;
    		} 
    		set{ 
    			if(m_FK_AnserId != value){
    				m_FK_AnserId = value; 
    				NotifyPropertyChanged("FK_AnserId"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((StudentTestDetail)dest).FK_TestId = ((StudentTestDetail)source).FK_TestId;
    		((StudentTestDetail)dest).FK_StudentId = ((StudentTestDetail)source).FK_StudentId;
    		((StudentTestDetail)dest).FK_QuestionId = ((StudentTestDetail)source).FK_QuestionId;
    		((StudentTestDetail)dest).FK_AnserId = ((StudentTestDetail)source).FK_AnserId;
    	}
    
    
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
    }
}
