//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class TestQuestion : BaseEntity
    {
    	private long m_TestId;
    	private long m_QuestionId;
    	private Nullable<double> m_Mark;
        public long TestId {
    		get{ 
    			return m_TestId;
    		} 
    		set{ 
    			if(m_TestId != value){
    				m_TestId = value; 
    				NotifyPropertyChanged("TestId"); 
                }
    		} 
    	}
        public long QuestionId {
    		get{ 
    			return m_QuestionId;
    		} 
    		set{ 
    			if(m_QuestionId != value){
    				m_QuestionId = value; 
    				NotifyPropertyChanged("QuestionId"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<double> Mark {
    		get{ 
    			return m_Mark;
    		} 
    		set{ 
    			if(m_Mark != value){
    				m_Mark = value; 
    				NotifyPropertyChanged("Mark"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((TestQuestion)dest).TestId = ((TestQuestion)source).TestId;
    		((TestQuestion)dest).QuestionId = ((TestQuestion)source).QuestionId;
    		((TestQuestion)dest).Mark = ((TestQuestion)source).Mark;
    	}
    
    
        public virtual Question Question { get; set; }
        public virtual Test Test { get; set; }
    }
}
