//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class UserSubjectRight : BaseEntity
    {
    	private int m_FK_TeacherId;
    	private int m_FK_SubjectId;
    	private int m_Right;
        public int FK_TeacherId {
    		get{ 
    			return m_FK_TeacherId;
    		} 
    		set{ 
    			if(m_FK_TeacherId != value){
    				m_FK_TeacherId = value; 
    				NotifyPropertyChanged("FK_TeacherId"); 
                }
    		} 
    	}
        public int FK_SubjectId {
    		get{ 
    			return m_FK_SubjectId;
    		} 
    		set{ 
    			if(m_FK_SubjectId != value){
    				m_FK_SubjectId = value; 
    				NotifyPropertyChanged("FK_SubjectId"); 
                }
    		} 
    	}
    	[DataMember]
        public int Right {
    		get{ 
    			return m_Right;
    		} 
    		set{ 
    			if(m_Right != value){
    				m_Right = value; 
    				NotifyPropertyChanged("Right"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((UserSubjectRight)dest).FK_TeacherId = ((UserSubjectRight)source).FK_TeacherId;
    		((UserSubjectRight)dest).FK_SubjectId = ((UserSubjectRight)source).FK_SubjectId;
    		((UserSubjectRight)dest).Right = ((UserSubjectRight)source).Right;
    	}
    
    
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
