//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Answer : BaseEntity
    {
    	private long m_AnswerId;
    	private string m_Content;
    	private long m_FK_QuestionId;
    	private bool m_IsAnswer;
        public long AnswerId {
    		get{ 
    			return m_AnswerId;
    		} 
    		set{ 
    			if(m_AnswerId != value){
    				m_AnswerId = value; 
    				NotifyPropertyChanged("AnswerId"); 
                }
    		} 
    	}
    	[DataMember]
        public string Content {
    		get{ 
    			return m_Content;
    		} 
    		set{ 
    			if(m_Content != value){
    				m_Content = value; 
    				NotifyPropertyChanged("Content"); 
                }
    		} 
    	}
    	[DataMember]
        public long FK_QuestionId {
    		get{ 
    			return m_FK_QuestionId;
    		} 
    		set{ 
    			if(m_FK_QuestionId != value){
    				m_FK_QuestionId = value; 
    				NotifyPropertyChanged("FK_QuestionId"); 
                }
    		} 
    	}
    	[DataMember]
        public bool IsAnswer {
    		get{ 
    			return m_IsAnswer;
    		} 
    		set{ 
    			if(m_IsAnswer != value){
    				m_IsAnswer = value; 
    				NotifyPropertyChanged("IsAnswer"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((Answer)dest).AnswerId = ((Answer)source).AnswerId;
    		((Answer)dest).Content = ((Answer)source).Content;
    		((Answer)dest).FK_QuestionId = ((Answer)source).FK_QuestionId;
    		((Answer)dest).IsAnswer = ((Answer)source).IsAnswer;
    	}
    
    
        public virtual Question Question { get; set; }
    }
}
