//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class MultiTestCopy : BaseEntity
    {
    	private int m_MultiTestCopyId;
    	private long m_FK_MultiTestId;
    	private string m_MultiTestCopyStructure;
        public int MultiTestCopyId {
    		get{ 
    			return m_MultiTestCopyId;
    		} 
    		set{ 
    			if(m_MultiTestCopyId != value){
    				m_MultiTestCopyId = value; 
    				NotifyPropertyChanged("MultiTestCopyId"); 
                }
    		} 
    	}
    	[DataMember]
        public long FK_MultiTestId {
    		get{ 
    			return m_FK_MultiTestId;
    		} 
    		set{ 
    			if(m_FK_MultiTestId != value){
    				m_FK_MultiTestId = value; 
    				NotifyPropertyChanged("FK_MultiTestId"); 
                }
    		} 
    	}
    	[DataMember]
        public string MultiTestCopyStructure {
    		get{ 
    			return m_MultiTestCopyStructure;
    		} 
    		set{ 
    			if(m_MultiTestCopyStructure != value){
    				m_MultiTestCopyStructure = value; 
    				NotifyPropertyChanged("MultiTestCopyStructure"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((MultiTestCopy)dest).MultiTestCopyId = ((MultiTestCopy)source).MultiTestCopyId;
    		((MultiTestCopy)dest).FK_MultiTestId = ((MultiTestCopy)source).FK_MultiTestId;
    		((MultiTestCopy)dest).MultiTestCopyStructure = ((MultiTestCopy)source).MultiTestCopyStructure;
    	}
    
    
        public virtual MultiTest MultiTest { get; set; }
    }
}
