//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NganHangEntities : DbContext
    {
        public NganHangEntities()
            : base(Common.DbHelper.ConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answers { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<LopHoc> LopHocs { get; set; }
        public DbSet<MultiTestCopy> MultiTestCopies { get; set; }
        public DbSet<MultiTestQuestion> MultiTestQuestions { get; set; }
        public DbSet<MultiTest> MultiTests { get; set; }
        public DbSet<Operation> Operations { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<SchoolInfo> SchoolInfos { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentTestDetail> StudentTestDetails { get; set; }
        public DbSet<StudentTest> StudentTests { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<SubjectsClass> SubjectsClasses { get; set; }
        public DbSet<SubjectsMultiTest> SubjectsMultiTests { get; set; }
        public DbSet<TeacherOperation> TeacherOperations { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<TestCopy> TestCopies { get; set; }
        public DbSet<TestQuestion> TestQuestions { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<UserSubjectRight> UserSubjectRights { get; set; }
    }
}
