//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class StudentTest : BaseEntity
    {
    	private long m_FK_StudenId;
    	private long m_FK_TestId;
    	private Nullable<double> m_Score;
    	private string m_Description;
    	private string m_QuestionStructure;
    	private Nullable<int> m_CorrectNo;
    	private Nullable<int> m_WrongNo;
    	private Nullable<int> m_NotDone;
    	private Nullable<int> m_DoneTime;
        public long FK_StudenId {
    		get{ 
    			return m_FK_StudenId;
    		} 
    		set{ 
    			if(m_FK_StudenId != value){
    				m_FK_StudenId = value; 
    				NotifyPropertyChanged("FK_StudenId"); 
                }
    		} 
    	}
        public long FK_TestId {
    		get{ 
    			return m_FK_TestId;
    		} 
    		set{ 
    			if(m_FK_TestId != value){
    				m_FK_TestId = value; 
    				NotifyPropertyChanged("FK_TestId"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<double> Score {
    		get{ 
    			return m_Score;
    		} 
    		set{ 
    			if(m_Score != value){
    				m_Score = value; 
    				NotifyPropertyChanged("Score"); 
                }
    		} 
    	}
    	[DataMember]
        public string Description {
    		get{ 
    			return m_Description;
    		} 
    		set{ 
    			if(m_Description != value){
    				m_Description = value; 
    				NotifyPropertyChanged("Description"); 
                }
    		} 
    	}
    	[DataMember]
        public string QuestionStructure {
    		get{ 
    			return m_QuestionStructure;
    		} 
    		set{ 
    			if(m_QuestionStructure != value){
    				m_QuestionStructure = value; 
    				NotifyPropertyChanged("QuestionStructure"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<int> CorrectNo {
    		get{ 
    			return m_CorrectNo;
    		} 
    		set{ 
    			if(m_CorrectNo != value){
    				m_CorrectNo = value; 
    				NotifyPropertyChanged("CorrectNo"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<int> WrongNo {
    		get{ 
    			return m_WrongNo;
    		} 
    		set{ 
    			if(m_WrongNo != value){
    				m_WrongNo = value; 
    				NotifyPropertyChanged("WrongNo"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<int> NotDone {
    		get{ 
    			return m_NotDone;
    		} 
    		set{ 
    			if(m_NotDone != value){
    				m_NotDone = value; 
    				NotifyPropertyChanged("NotDone"); 
                }
    		} 
    	}
    	[DataMember]
        public Nullable<int> DoneTime {
    		get{ 
    			return m_DoneTime;
    		} 
    		set{ 
    			if(m_DoneTime != value){
    				m_DoneTime = value; 
    				NotifyPropertyChanged("DoneTime"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((StudentTest)dest).FK_StudenId = ((StudentTest)source).FK_StudenId;
    		((StudentTest)dest).FK_TestId = ((StudentTest)source).FK_TestId;
    		((StudentTest)dest).Score = ((StudentTest)source).Score;
    		((StudentTest)dest).Description = ((StudentTest)source).Description;
    		((StudentTest)dest).QuestionStructure = ((StudentTest)source).QuestionStructure;
    		((StudentTest)dest).CorrectNo = ((StudentTest)source).CorrectNo;
    		((StudentTest)dest).WrongNo = ((StudentTest)source).WrongNo;
    		((StudentTest)dest).NotDone = ((StudentTest)source).NotDone;
    		((StudentTest)dest).DoneTime = ((StudentTest)source).DoneTime;
    	}
    
    
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
    }
}
