//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCO
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class TestCopy : BaseEntity
    {
    	private int m_TestCopyId;
    	private long m_FK_TestId;
    	private string m_TestCopyStructure;
        public int TestCopyId {
    		get{ 
    			return m_TestCopyId;
    		} 
    		set{ 
    			if(m_TestCopyId != value){
    				m_TestCopyId = value; 
    				NotifyPropertyChanged("TestCopyId"); 
                }
    		} 
    	}
    	[DataMember]
        public long FK_TestId {
    		get{ 
    			return m_FK_TestId;
    		} 
    		set{ 
    			if(m_FK_TestId != value){
    				m_FK_TestId = value; 
    				NotifyPropertyChanged("FK_TestId"); 
                }
    		} 
    	}
    	[DataMember]
        public string TestCopyStructure {
    		get{ 
    			return m_TestCopyStructure;
    		} 
    		set{ 
    			if(m_TestCopyStructure != value){
    				m_TestCopyStructure = value; 
    				NotifyPropertyChanged("TestCopyStructure"); 
                }
    		} 
    	}
    
    	protected override void CopyFromEntity(BaseEntity source, BaseEntity dest){
    		((TestCopy)dest).TestCopyId = ((TestCopy)source).TestCopyId;
    		((TestCopy)dest).FK_TestId = ((TestCopy)source).FK_TestId;
    		((TestCopy)dest).TestCopyStructure = ((TestCopy)source).TestCopyStructure;
    	}
    
    
        public virtual Test Test { get; set; }
    }
}
